version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: tenantflow-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: tenantflow_dev
      POSTGRES_USER: tenantflow
      POSTGRES_PASSWORD: tenantflow_password

    ports:
      - "5432:5432"

    volumes:
      - tenantflow_postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    container_name: tenantflow-api

    depends_on:
      - postgres

    ports:
      - "5024:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

  frontend:
    build:
      context: ./frontend
    container_name: tenantflow-frontend

    depends_on:
      - api

    ports:
      - "3000:3000"

    environment:
      STACK_SECRET_SERVER_KEY: ${STACK_SECRET_SERVER_KEY}
      NEXT_PUBLIC_STACK_PROJECT_ID: ${NEXT_PUBLIC_STACK_PROJECT_ID}
      NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: ${NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY}

volumes:
  tenantflow_postgres_data:
