version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: tenantflow-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: tenantflow_dev
      POSTGRES_USER: tenantflow
      POSTGRES_PASSWORD: tenantflow_password

    ports:
      - "5432:5432"

    volumes:
      - tenantflow_postgres_data:/var/lib/postgresql/data

volumes:
  tenantflow_postgres_data:
