// UserStatus Enum: defines the possible statuses of a user account in a system.
// Each status represents a different state of the user's account, which can affect their access and permissions within the system.
// ===
// ACTIVE: The user is active and can access the system.
// INACTIVE: The user is inactive and cannot access the system.
// PENDING_VERIFICATION: The user's account is pending verification, possibly awaiting email confirmation or admin approval.
// FROZEN: The user's account is frozen, possibly due to security reasons or policy violations.
// DELETED: The user's account has been deleted and cannot be recovered.
export enum UserStatus {
  ACTIVE = "active",
  INACTIVE = "inactive",
  PENDING_VERIFICATION = "pending_verification",
  FROZEN = "frozen",
  DELETED = "deleted",
}

/**
 * AuthFactorType Enum: defines the types of authentication factors that can be used for user authentication in a system.
 * Each type represents a different method of verifying a user's identity.
 * ===
 * PASSWORD: Authentication using a password.
 * TOTP: Time-based One-Time Password, a temporary code generated by an authenticator app.
 * PASSKEY: Authentication using a passkey, which is a modern, password-less authentication method that uses cryptographic keys.
 * BIOMETRIC: Authentication using biometric data, such as fingerprint or facial recognition.
 * SECURITY_KEY: Authentication using a physical security key, such as a YubiKey,
 *   which provides strong protection against phishing attacks.
 */
export enum AuthFactorType {
  PASSWORD = "password",
  TOTP = "totp",
  PASSKEY = "passkey",
  BIOMETRIC = "biometric",
  SECURITY_KEY = "security_key",
}

/**
 * UserTokenType Enum: defines the types of verification tokens that can be used for various user verification processes in a system.
 * Each type represents a different purpose for which the token is generated.
 * ===
 * EMAIL_VERIFICATION: A token used for verifying a user's email address,
 *   typically sent as part of the account registration or email change process.
 * PASSWORD_RESET: A token used for resetting a user's password, typically sent when a user requests a password reset.
 * MFA_ENROLLMENT: A token used for enrolling a user in multi-factor authentication (MFA), typically sent during the MFA setup process.
 * MFA_CHALLENGE: A token used for challenging a user during the MFA authentication process,
 *   typically generated when a user attempts to log in and is required to provide an additional authentication factor.
 */
export enum UserTokenType {
  EMAIL_VERIFICATION = "email_verification",
  PASSWORD_RESET = "password_reset",
  MFA_ENROLLMENT = "mfa_enrollment",
  MFA_CHALLENGE = "mfa_challenge",
}

/**
 * TenantStatusType Enum: defines the possible statuses of a tenant in a multi-tenant system.
 * Each status represents a different state of the tenant, which can affect its availability and functionality within the system.
 * ===
 * ACTIVE: The tenant is active and can access the system's features and services.
 * INACTIVE: The tenant is inactive and cannot access the system's features and services,
 *   possibly due to non-payment or administrative action.
 * VERIFIED: The tenant is verified, meaning it has completed any necessary verification processes
 *   and be recognized as a well-known tenant in the system, which may grant it additional privileges or trust.
 * SUSPENDED: The tenant is suspended and temporarily cannot access the system's features and services,
 *   possibly due to policy violations or security issues.
 * ARCHIVED: The tenant is archived and cannot access the system's features and services,
 *   but its data is retained in the system for historical or auditing purposes.
 * DELETED: The tenant has been deleted and cannot be recovered,
 *   meaning all data associated with the tenant is permanently removed from the system.
 */
export enum TenantStatusType {
  ACTIVE = "active",
  INACTIVE = "inactive",
  VERIFIED = "verified",
  SUSPENDED = "suspended",
  ARCHIVED = "archived",
  DELETED = "deleted",
}

/**
 * TenantMembershipStatusType Enum: defines the possible statuses of a tenant membership in a multi-tenant system.
 * Each status represents a different state of the tenant membership,
 *   which can affect the user's access and permissions within the tenant.
 * ===
 * ACTIVE: The tenant membership is active, and the user has access to the tenant's features and services.
 * INACTIVE: The tenant membership is inactive, and the user does not have access to the tenant's features and services,
 *   possibly due to administrative action or the user's choice to leave the tenant.
 * PENDING: The tenant membership is pending, meaning the user has been invited to join the tenant
 *   but has not yet accepted the invitation.
 * SUSPENDED: The tenant membership is suspended, and the user temporarily does not have access
 *   to the tenant's features and services, possibly due to policy violations or security issues.
 * REMOVED: The tenant membership has been removed, and the user no longer has access to the tenant's features and services,
 *   meaning the user's association with the tenant has been permanently severed.
 */
export enum TenantMembershipStatusType {
  ACTIVE = "active",
  INACTIVE = "inactive",
  PENDING = "pending",
  SUSPENDED = "suspended",
  REMOVED = "removed",
}

/**
 * TenantCustomerStatusType Enum: defines the possible statuses of a tenant customer in a multi-tenant system.
 * Each status represents a different state of the tenant customer, which can affect their billing and access to the system's features and services.
 * ===
 * ACTIVE: The tenant customer is active and can access the system's features and services, and is in good standing with their billing.
 * INACTIVE: The tenant customer is inactive and cannot access the system's features and services,
 *   possibly due to non-payment or administrative action.
 * PAST_DUE: The tenant customer has an outstanding payment that is past due,
 *   which may result in restricted access to the system's features and services until the payment is resolved.
 * CANCELED: The tenant customer's subscription has been canceled, and they cannot access the system's features and services,
 *   but their data may still be retained in the system for a certain period.
 * DELETED: The tenant customer has been deleted and cannot be recovered,
 *   meaning all data associated with the tenant customer is permanently removed from the system.
 */
export enum TenantCustomerStatusType {
  ACTIVE = "active",
  INACTIVE = "inactive",
  PAST_DUE = "past_due",
  CANCELED = "canceled",
  DELETED = "deleted",
}

/**
 * TenantProjectStatusType Enum: defines the possible statuses of a tenant project in a multi-tenant system.
 * Each status represents a different state of the tenant project, which can affect its visibility and accessibility within the system.
 * ===
 * ACTIVE: The tenant project is active and can be accessed and modified by users with the appropriate permissions.
 * INACTIVE: The tenant project is inactive and cannot be accessed or modified,
 *   possibly due to administrative action or the project's completion.
 * COMPLETED: The tenant project has been completed and is read-only, meaning it can be viewed but not modified,
 *   and may be moved to an archive for completed projects.
 * ARCHIVED: The tenant project is archived and cannot be accessed or modified,
 *   but its data is retained in the system for historical or auditing purposes.
 * DELETED: The tenant project has been deleted and cannot be recovered,
 *   meaning all data associated with the tenant project is permanently removed from the system.
 */
export enum TenantProjectStatusType {
  ACTIVE = "active",
  INACTIVE = "inactive",
  COMPLETED = "completed",
  ARCHIVED = "archived",
  DELETED = "deleted",
}

/**
 * TenantProjectTaskStatusType Enum: defines the possible statuses of a tenant project task in a multi-tenant system.
 * Each status represents a different state of the tenant project task, which can affect its visibility and accessibility within the system.
 * ===
 * ACTIVE: The tenant project task is active and can be accessed and modified by users with the appropriate permissions.
 * INACTIVE: The tenant project task is inactive and cannot be accessed or modified,
 *   possibly due to administrative action or the task's completion.
 * COMPLETED: The tenant project task has been completed and is read-only, meaning it can be viewed but not modified,
 *   and may be moved to an archive for completed tasks.
 * ARCHIVED: The tenant project task is archived and cannot be accessed or modified,
 *  but its data is retained in the system for historical or auditing purposes.
 * DELETED: The tenant project task has been deleted and cannot be recovered,
 *   meaning all data associated with the tenant project task is permanently removed from the system.
 */
export enum TenantProjectTaskPriorityType {
  LOW = "low",
  MEDIUM = "medium",
  HIGH = "high",
  CRITICAL = "critical",
}

/**
 * TenantProjectTaskStatusType Enum: defines the possible statuses of a tenant project task in a multi-tenant system.
 * Each status represents a different state of the tenant project task, which can affect its visibility and accessibility within the system.
 * ===
 * TODO: The tenant project task is yet to be started and can be accessed and modified by users with the appropriate permissions.
 * IN_PROGRESS: The tenant project task is currently being worked on and can be accessed and modified by users
 *   with the appropriate permissions.
 * IN_REVIEW: The tenant project task is under review and can be accessed and modified by users with the appropriate permissions.
 * BLOCKED: The tenant project task is blocked and cannot be progressed until the blocking issue is resolved,
 *   but it can still be accessed and modified by users with the appropriate permissions.
 * DONE: The tenant project task has been completed and is read-only, meaning it can be viewed but not modified,
 *  and may be moved to an archive for completed tasks.
 * DEFERRED: The tenant project task has been deferred and is temporarily on hold,
 *   meaning it cannot be progressed until it is reactivated,
 *   but it can still be accessed and modified by users with the appropriate permissions.
 * CANCELLED: The tenant project task has been cancelled and cannot be recovered,
 *   meaning all data associated with the tenant project task is permanently removed from the system.
 */
export enum TenantProjectTaskStatusType {
  TODO = "todo",
  IN_PROGRESS = "in_progress",
  IN_REVIEW = "in_review",
  BLOCKED = "blocked",
  DONE = "done",
  DEFERRED = "deferred",
  CANCELLED = "cancelled",
}
