namespace TenantFlow.Core.Enums
{
  /// <summary>
  /// AuthFactorType Enum: defines the types of authentication factors that can be used for user authentication in a system.
  /// Each type represents a different method of verifying a user's identity.
  /// ---
  /// Password: A traditional authentication factor where the user provides a secret password.
  /// TOTP: Time-based One-Time Password, a temporary code generated by an authenticator app, used for two-factor authentication (2FA).
  /// PassKey: A modern authentication factor that uses public key cryptography for secure authentication, typically implemented through WebAuthn or similar protocols.
  /// Biometric: An authentication factor that uses unique biological characteristics of the user, such as fingerprints or facial recognition, for identity verification.
  /// SecurityKey: A physical device that provides an additional layer of security for user authentication, typically through USB or NFC.
  /// </summary>
  /// 
    public enum AuthFactorType
    {
      Password,
      TOTP,
      PassKey,
      Biometric,
      SecurityKey
    }
}